name: pyml
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - awkward
      - lightgbm
      - matplotlib
      - numpy
      - optuna
      - pandas
      - pyyaml
      - scikit-learn
      - shap
      - torch
      - uproot
