metadata:
  purpose: "Binary classification (signal vs background) config for ML training/tuning"
  notes: "Paths are resolved relative to this file unless absolute."

data:
  files:
    - ../../data/input/SigmaNCusp.root
    - ../../data/input/QFLambda.root
    - ../../data/input/QFSigmaZ.root
  tree_name: g4s2s
  label_column: label
  label_mapping:
    signal_labels: [1]          # SigmaNCusp
    background_labels: [2, 3]   # QFLambda, QFSigmaZ
  feature_columns:
    - t0_theta
    - t0_phi
    - t0_dedx
    - t1_theta
    - t1_phi
    - t1_dedx
    - t2_theta
    - t2_phi
    - t2_dedx
  fraction: 1.0                  # Downsample ratio (use <1.0 for quick tests)
    
tuning:
  fraction: 0.3                  # Downsample ratio for faster tuning
  val_split: 0.2                 # Validation split during tuning
  epochs: 10
  n_trials: 25
  batch_size_options: [64, 128, 256]
  num_workers: 2
  direction: maximize
  search_space:
    n_layers: {min: 2, max: 4}
    hidden_units: {min: 64, max: 256}
    dropout: {min: 0.1, max: 0.5}
    lr: {min: 1.0e-4, max: 1.0e-2}
  best_params_path: ../tune/tuned_params.json
  study_summary_path: ../../data/output/tuning_trials.csv

training:
  fraction: 1.0                  # Use full dataset for final training
  val_split: 0.2
  epochs: 50
  num_workers: 2
  model_output_path: ../../data/output/model.pth
  best_params_path: ../tune/tuned_params.json
  metrics_output_path: ../../data/output/train_metrics.json
  predictions_output_path: ../../data/output/predictions.csv
  plots_dir: ../../data/output/plots
  # batch_size: 128              # Optional override instead of tuned batch size

device: auto                     # Set to "cuda" or "cpu" to force a device
