# E90ML config

metadata:
  purpose: "Binary classification (SigmaNCusp vs background)"
  notes: "Labels: SigmaNCusp=1 (signal), QFLambda=2, QFSigmaZ=3."

data:
  files:
    SigmaNCusp: SigmaNCusp.root   # looked up under data/input
    QFLambda: QFLambda.root
    QFSigmaZ: QFSigmaZ.root
  tree_name: g4s2s
  label_column: label
  feature_columns:
    - t0_theta
    - t0_phi
    - t0_dedx
    - t1_theta
    - t1_phi
    - t1_dedx
    - t2_theta
    - t2_phi
    - t2_dedx
  fraction: 1.0
    
tuning:
  seed: 42
  fraction: 0.3
  val_split: 0.2
  epochs: 10
  n_trials: 25
  batch_size_options: [64, 128, 256]
  num_workers: 8
  direction: maximize
  search_space:
    n_layers: {min: 2, max: 4}
    hidden_units: {min: 64, max: 256}
    dropout: {min: 0.1, max: 0.5}
    lr: {min: 1.0e-4, max: 1.0e-2}
  best_params_path: tuned_params.json         # saved under param/tune
  study_summary_path: tuning_trials.csv       # saved under data/output

training:
  seed: 42
  fraction: 1.0
  val_split: 0.2
  epochs: 50
  patience: 10
  num_workers: 8
  model_output_path: demo.pth                   # saved under param/pth
  scaler_output_path: demo_scaler.pkl           # saved under param/pth
  best_params_path: tuned_params.json           # read from param/tune
  metrics_output_path: demo_metrics.json        # saved under data/output
  predictions_output_path: demo_predictions.csv # saved under data/output
  plots_dir: plots                              # saved under data/output/plots

device: auto
