# E90ML config
# - labels: SigmaNCusp=1 (signal), QFLambda=2, QFSigmaZ=3
# - Input ROOTs live in data/input
# - Tuned params go to param/tune
# - Models go to param/pth
# - Metrics/predictions/plots go to data/output

data:
  files:                        # ROOT file names under data/input
    SigmaNCusp: SigmaNCusp.root
    QFLambda: QFLambda.root
    QFSigmaZ: QFSigmaZ.root
  tree_name: g4s2s
  label_column: label
  feature_columns:
    - t0_theta
    - t0_phi
    - t0_dedx
    - t1_theta
    - t1_phi
    - t1_dedx
    - t2_theta
    - t2_phi
    - t2_dedx
  fraction: 1.0                  # Downsample ratio (use <1.0 for quick tests)
    
tuning:
  fraction: 0.3                  # Downsample ratio for faster tuning
  val_split: 0.2                 # Validation split during tuning
  epochs: 10
  n_trials: 25
  batch_size_options: [64, 128, 256]
  num_workers: 8
  direction: maximize
  search_space:
    n_layers: {min: 2, max: 4}
    hidden_units: {min: 64, max: 256}
    dropout: {min: 0.1, max: 0.5}
    lr: {min: 1.0e-4, max: 1.0e-2}
  best_params_path: tuned_params.json    # saved to param/tune
  study_summary_path: tuning_trials.csv  # saved to data/output

training:
  fraction: 1.0                  # Use full dataset for final training
  val_split: 0.2
  epochs: 50
  num_workers: 8
  model_output_path: demo.pth                # saved to param/pth
  best_params_path: tuned_params.json        # read from param/tune; should match tuning output
  metrics_output_path: demo_metrics.json     # saved to data/output
  predictions_output_path: demo_predictions.csv  # saved to data/output
  plots_dir: plots                           # subdirectory under data/output
  # batch_size: 128              # Optional override instead of tuned batch size

device: auto                     # Set to "cuda" or "cpu" to force a device
