# E90ML config

metadata:
  purpose: "Binary classification (SigmaNCusp vs background)"
  notes: "Labels: SigmaNCusp=1 (signal), QFLambda=2, QFSigmaZ=3."

data:
  files:
    SigmaNCusp: SigmaNCusp.root   # looked up under data/input
    QFLambda: QFLambda.root
    QFSigmaZ: QFSigmaZ.root
  tree_name: g4s2s
  label_column: label
  feature_columns:
    - t0_ux
    - t0_uy
    - t0_uz
    - t0_dedx
    - t1_ux
    - t1_uy
    - t1_uz
    - t1_dedx
    - t2_ux
    - t2_uy
    - t2_uz
    - t2_dedx
  fraction: 1.0
    
tuning:
  seed: 42               # RNG seed for tuning splits/shuffling (leave blank to disable)
  fraction: 0.3
  val_split: 0.2
  epochs: 20
  n_trials: 100
  batch_size_options: [1024, 2048, 4096]
  num_workers: 0
  direction: maximize
  search_space:
    n_layers: {min: 2, max: 6}
    hidden_units: {min: 64, max: 256}
    dropout: {min: 0.1, max: 0.5}
    lr: {min: 1.0e-4, max: 1.0e-2}
  tune_params_file: tuned_params.json         # saved under param/tune
  study_summary_file: tuning_trials.csv       # saved under data/output
  plots:
    dir: plots                                # saved under data/output
    optimization_history_file: optimization_history.png
    param_importances_file: param_importances.png
    param_slice_file: param_slice.png

training:
  seed: 90                                     # RNG seed for training splits/shuffling (leave blank to disable)
  fraction: 1.0
  val_split: 0.2
  epochs: 50
  patience: 10
  num_workers: 8
  checkpoint_file: demo.pth                     # saved under param/pth (used for resume; same as model output)
  model_output_file: demo.pth                   # saved under param/pth
  scaler_output_file: demo_scaler.pkl           # saved under param/pth
  best_params_file: tuned_params.json           # read from param/tune
  metrics_output_file: demo_metrics.json        # saved under data/output
  predictions_output_file: demo_predictions.csv # saved under data/output
  plot_output_file: demo.png                    # saved under data/output

test:
  fraction: 1.0
  batch_size: 128
  num_workers: 8
  metrics_output_file: demo_test_metrics.json        # saved under data/output
  predictions_output_file: demo_test_predictions.csv # saved under data/output

device: auto
